# 安装目录 
software_dir: '/root/binary_pkg'
k8s_work_dir: '/opt/kubernetes'
etcd_work_dir: '/opt/etcd'
tmp_dir: '/tmp/k8s'

# 容器网络
service_cidr: '10.0.0.0/24'
cluster_dns: '10.0.0.2'
pod_cidr: '10.244.0.0/16' # 与CNI插件网络一致
service_nodeport_range: '30000-32767'
cluster_domain: 'cluster.local'

# 高可用，如果部署单Master，该项忽略
vip: '192.168.31.88'
nic: 'ens33' 

# 自签证书可信任IP列表，为方便扩展，可添加多个预留IP
cert_hosts:
  # 包含所有LB、VIP和Master IP
  k8s:
    - 192.168.122.112
    - 192.168.122.19
    - 192.168.122.183
  # 包含所有etcd节点IP
  etcd:
    - 192.168.122.112
    - 192.168.122.19
    - 192.168.122.183
